### PR TITLE
Added Arty A7 support

### PR DESCRIPTION
**Pull request by riktw**
This PR adds the Digitlent Arty A7 board. 
Minor changed had to be made in usb_dfu_ctrl_ep.v for Vivado to synthesize it, the rest is the Vivado project for the board.

### CODE REVIEW

**Comment by oskirby** [comment]
I've been trying to look over this and get a handle for the scope of this work, I'm finding the commit a bit overwhelming since it's full of all kinds of logs and duplicated files from the Vivado build process. At the very least I would want to see a .gitignore file that prevents stuff like the build logs and duplicate source files.

I've been trying to test out your work by building it for an Arty-A7 (100T) that I have lying around, but it occurs to me that there isn't a USB connector on it to the FPGA. Is there a particular pmod that you were using for this design? If so we should probably document that somewhere.

**Comment by oskirby** [comment]
I've been playing with this a bit, and I managed to get it working on my Arty-A7 (my work is here: https://github.com/oskirby/tinydfu-bootloader/tree/arty-a7).

I found a problem that the DFU bootloader is unable to write anything above address 0x20000 into flash, this seems to be that the Arty-A7 has a weird flash chip that doesn't support 4kB erase sizes outside of the first 32 sectors of the chip. This would probably go unnoticed on the 35T-sized version since the DFU bootloader image would be a lot smaller.

**Comment by riktw** [comment]
I have no issues writing the entire flash. Currently the first 2MB are reserved for the bootloader, so the user image is written from 0x20000 to 0x40000. After some digging it seems newer boards have S25FL128 flash, with the issue regarding the first 32 sectors and older boards have the ​N25Q128A flash with no such weirdness. 
Info from https://reference.digilentinc.com/reference/programmable-logic/arty-a7/reference-manual section 5.2

I can try and clean up the PR, or base it on your tree as that looks a lot neater then my approach, but if it only works on older arty boards it might not be too useful.
Would you prefer me to clean it up one way or another and add a disclaimed regarding the flash chips, or would you prefer to decline it as support for only older Arty boards is not exactly ideal?

**Comment by oskirby** [comment]
It seems that we can support both the N25Q128A and S25FL128 flash parts by using the 64kB sector erase command instead, so I've committed another fix that should get it working again (see: ad13c93f6506eddd855c3f9bb2c757b836bce9c6).

I think it's a lot cleaner to use a tcl script to build the bootloader rather than checking in a Vivado project into git, it would be great if you could rebase your work off my branch to see if it still works for your board.

**Comment by riktw** [comment]
I had a look at the arty-a7 branch and it works as expected here on my arty-a7 board. 
I can write to the entire flash and the bootloader button works as expected, the LEDs are a nice bonus :)

Looking at the PR, I think all functionality and some more is present in your arty-a7 branch, so I would say this PR can be closed if you agree on that.

**Comment by oskirby** [comment]
Thank you for testing it out, I'm going to close this PR and merge the arty-a7 branch instead.

**Pull request closed without merging**
